# Generated by Django 4.2.16 on 2024-09-27 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("discord_user_id", models.CharField(max_length=255, unique=True)),
                ("discord_username", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VoiceChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "discord_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="discord.discorduser"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyVoiceChatStat",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("total_duration", models.DurationField(default=0)),
                ("difference_from_previous_day", models.DurationField(blank=True, null=True)),
                (
                    "discord_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="discord.discorduser"),
                ),
            ],
            options={
                "unique_together": {("discord_user", "date")},
            },
        ),
    ]
